project:
  type: website
  output-dir: my-quarto-site

website:
  title: "My Quarto site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - contact.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



