project:
  type: website

website:
  title: "My Quarto site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: devops_pra.qmd
        text: DevOps_PRA
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact


format:
  html:
    theme: minty
    toc: true



