project: 
  type: website

website:
  title: "today"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: PRA-01
        href: pra-01.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

extensions:
  - mermaid
